Parameters:
  VPC:
    Type: AWS::EC2::VPC::Id
    Description: The ID of the VPC to use for the ECS cluster
  Subnets:
    Type: List<AWS::EC2::Subnet::Id>
    Description: The IDs of the subnets to use for the ECS cluster

Resources:
  MyCluster:
    Type: 'AWS::ECS::Cluster'

  MyTaskDefinition:
    Type: 'AWS::ECS::TaskDefinition'
    Properties:
      Family: !Join ['', [java,-, td]]
      NetworkMode: 'awsvpc'
      RequiresCompatibilities:
        - 'FARGATE'
      Cpu:  512
      Memory: 1024
      ExecutionRoleArn: arn:aws:iam::19016455458:role/ecsTaskExecutionRole
      TaskRoleArn: arn:aws:iam::19016455458:role/ecsTaskExecutionRole
      ContainerDefinitions:
        - Name: java-app
          Image: 19016455458.dkr.ecr.eu-west-1.amazonaws.com/app-1:latest
          PortMappings:
            - ContainerPort: 3000
  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for ECS
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 3000
          ToPort: 3000
          CidrIp: 0.0.0.0/0
  MyService:
    Type: 'AWS::ECS::Service'
    Properties:
      ServiceName: java-service
      Cluster: !Ref MyCluster
      TaskDefinition: !Ref MyTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          AssignPublicIp: ENABLED
          Subnets: !Ref Subnets
          SecurityGroups:
            - !Ref SecurityGroup
